### ISSUE TITLE
Zahlungsreferenz nicht gefunden oder bereits bezahlt.

### ISSUE THREAD

**Issue by derWalter** [metarheinmain/camptix-payment-banktransfer#9]
habe gerade eine testinstallation gemacht,
mit vanilla wp ohne zusatzplugins, bis auf camptix und camptix-payment-banktransfer.

klappt alles so weit, bis auf dass, wenn ich den per email erhaltenen verwendungszweck
als bezahlt eintragen will (mit oder ohne eingabe vom jeweiligen betrag) erhalte ich immer diese fehlermeldung.

**Comment by raphaelm** [comment]
Du bist schon der zweite in den letzten Tagen mit dem Problem. Werde mir das wohl mal anschauen müssen :(

**Comment by raphaelm** [comment]
Ich habe mir jetzt auch eine Testinstallation gemacht und das Problem trat *nicht* auf. Ich habe folgendes getan:

* Installation WordPress 4.2.2
* Installation CampTix 1.4.2
* Installation camptix-payment-banktransfer die neuste Version aus dem git
* Konfigurieren von Banküberweisung als aktivierte Zahlungsart
* Einfügen von [bankdetails] in die E-Mail-Vorlagen
* Einfügen von [camptix] in eine Seite
* Anlegen eines Tickets zu 1 USD
* Kauf eines Tickets
* Ich habe darauf eine E-Mail erhalten, in der stand, dass ich mit "Verwendungszweck: 7515572adf14be92" bezahlen soll
* Eingabe von "7515572adf14be92" und "1" USD im Adminbereich unter Banküberweisung
* Das Ticket wurde als bezahlt markiert und der User hat das per Mail bestätigt bekommen.

Probleme, die ich nicht sehe, kann ich leider kaum beheben :(

**Comment by derWalter** [comment]
genau wie ich, nur dass ich schon ein wenig mehr gemacht habe,
site siehe: http://derwalter.com/lip


server ist ein fremdgehosteter iis,
werde später oder morgen mal alle wp debug options anwerden und gucken
was der so macht und wo das schiefgeht.

melde mich asap!

**Comment by derWalter** [comment]
okay, schnell apache, php5, mysql aufgesetzt und dann deiner anleitung gefolgt... jetzt wirft mir campix nur "An error has occurred." aus :P

unabhängig davon ob payment aktiviert ist oder nicht...


 ich glaub ich lass das mal lieber für heute ^^

**Comment by derWalter** [comment]
okay, an error, war der klassiker dass ich in einen post statt einer page getestet habe.

irgendwie krieg ich hier ausm netzwerk keine maisl rausgesandt, deshalb habe ich einfach
noch mal am selben host ein komplett neues wordpress aufgesetzt, mit dem selben ergebnis.

" Payment reference not found or already marked as payed. "

wie kann ich dich dabei unterstützen den fehler ausfindig zu machen?


lg
walter

**Comment by raphaelm** [comment]
> wie kann ich dich dabei unterstützen den fehler ausfindig zu machen?

Wenn ich das wüsste. Wenn das ein komplett neues WordPress ohne Nutzerdaten ist, in dem das auftritt, kannst du mir dann einfach mal einen vollen Dump der MySQL-Datenbank schicken (an mail@raphaelmichel.de)? Zusammen mit der Info, was genau du im Adminbereich eingibst?

Abgelegt werden die in post_meta, glaube ich. Auch wenn das lang her ist, dass ich das Plugin geschrieben habe…

Viele Grüße
Raphael

**Comment by derWalter** [comment]
so, habe noch mal eine test install gemacht mit dem selben ergebniss.

gemacht habe ich genau das:
Installation WordPress 4.2.2 (tar gezogen entpackt mit filezilla hochgeladen)
Installation CampTix 1.4.2 (über das wordpress menu installiert)
Installation camptix-payment-banktransfer die neuste Version aus dem git (git lokal gezogen ordner camtpix-payment-banktransfer order in /plugins/ geladen)
Konfigurieren von Banküberweisung als aktivierte Zahlungsart
Einfügen von [bankdetails] in die E-Mail-Vorlagen
Einfügen von [camptix] in eine Seite
Anlegen eines Tickets zu 1 USD
Kauf eines Tickets
Ich habe darauf eine E-Mail erhalten, in der stand, dass ich mit "Verwendungszweck: 7515572adf14be92" bezahlen soll

ab da wars bei mir dann leider vorbei

**Comment by raphaelm** [comment]
Schickst du mir einen Export der Datenbank?

**Comment by derWalter** [comment]
sollte schon in deiner inbox sein :)

falls du zugang zur db, wp install oder ftp brauchst gib bescheid.

**Comment by raphaelm** [comment]
Seltsam ist auch, dass wir beide den Code 7515572adf14be92 erhalten haben :D

**Comment by raphaelm** [comment]
In der Mail stand wirklich 7515572adf14be92? Dann ist das wohl die Problemquelle. In der Datenbank steht 58955769a4d29a6c. Probier mal, ob der funktioniert.

**Comment by derWalter** [comment]
hehe, nein, den code habe ich nicht erhalten,
sondern nur von dir copiert.
ich habe natürlich 58955769a4d29a6c verwendet

**Comment by raphaelm** [comment]
Fixed in a4ad3d2960c2961650655b5b45a17f35beaac449
